apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app
  labels:
    app: student
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student
  template:
    metadata:
      labels:
        app: student
    spec:
      containers:
      - name: student
        image: tallapakam/student:latest
        ports:
        - containerPort: 8181